In [1]:
 import numpy as np

In [4]:
for i in (range(6)):
    print(i)

0
1
2
3
4
5


In [3]:
a

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 0]]

In [10]:
a.shape()

TypeError: 'tuple' object is not callable

In [9]:
a = np.array(a)

In [11]:
a


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [13]:
a.shape

(5, 2)

In [15]:
a[(1, 2)][:]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [21]:
b = np.array([1, 1, 4])

In [22]:
b

array([1, 1, 4])

In [23]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [24]:
a[b[:], :] + 1

array([[ 4,  5],
       [ 4,  5],
       [10,  1]])

In [25]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [26]:
b

array([1, 1, 4])

In [27]:
np.add.at(a, b, 1)

In [28]:
a

array([[ 1,  2],
       [ 5,  6],
       [ 5,  6],
       [ 7,  8],
       [10,  1]])

In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
a[:-5]

[0, 1, 2, 3, 4]

In [6]:
a[5:]

[5, 6, 7, 8, 9]

In [7]:
a[-7:]

[3, 4, 5, 6, 7, 8, 9]

In [8]:
a[:-7]

[0, 1, 2]

In [9]:
a[-7]

3