In [1]:
import numpy as np


In [2]:
from cs231n.im2col import im2col_indices

In [3]:
im2col_indices


<function cs231n.im2col.im2col_indices>

In [2]:
a = [[1, 2, 3], [4, 5, 6]]

In [7]:
a[0:1]

[[1, 2, 3]]

In [3]:
a

[[1, 2, 3], [4, 5, 6]]

In [4]:
b = [0, 1, 2]

In [5]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
b = [1, 1, 2]

In [7]:
a[b, range(3)]

TypeError: list indices must be integers or slices, not tuple

In [8]:
a = np.array(a)

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b = np.array(b)

In [11]:
b

array([1, 1, 2])

In [15]:
a[b, range(3)]

array([4, 5, 3])

In [13]:
b[2] = 0

In [14]:
b

array([1, 1, 0])